### ISSUE TITLE
some pages from google search directs to not found(404)

### ISSUE THREAD

**Issue by oshai** [kotlinresources/kotlin-resources#21]
For example: 
https://www.kotlinresources.com/library/assertk/
https://www.kotlinresources.com/library/kotlin-logging/
with this google search showing it: https://www.google.co.il/search?q=kotlin+resources+kotlin-logging
And the lib is here: https://github.com/MicroUtils/kotlin-logging

**Comment by oshai** [comment]
After digging a bit more I found that kotlin-logging is configured: https://github.com/kotlinresources/kotlin-resources/blob/master/resources/libraries/microutils-kotlin-logging.json  
So it seems more reasonable this is some kind of a bug of change in url's

**Comment by gyulavoros** [comment]
Thanks for reporting the issue, we'll look into it.

**Comment by oshai** [comment]
looks like it is fixed.
